name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build containers with Docker Compose
        run: docker-compose build

      # Optional: run backend tests (adjust to your test runner)
      - name: Run backend tests
        run: docker-compose run --rm backend pytest

      # Optional: Start the stack to ensure it boots up
      - name: Start containers
        run: docker-compose up -d

      - name: List running containers
        run: docker ps

      - name: Shut down containers
        run: docker-compose down